<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\HomeOfficeRequestController;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Public Routes
|--------------------------------------------------------------------------
|
| These routes are accessible without authentication. They typically include
| your application's welcome page, login, registration, and other public-facing features.
|
*/

Route::get('/', function () {
    return Inertia::render('Welcome', [
        'canLogin' => Route::has('login'),
        'canRegister' => Route::has('register'),
        'laravelVersion' => Application::VERSION,
        'phpVersion' => PHP_VERSION,
    ]);
});

/*
|--------------------------------------------------------------------------
| Authentication Routes
|--------------------------------------------------------------------------
|
| Laravel Breeze (or Fortify/Jetstream) simplifies authentication routing.
| This file is automatically generated and includes routes for login,
| registration, password reset, and email verification.
|
*/

require __DIR__ . '/auth.php';

/*
|--------------------------------------------------------------------------
| Authenticated Routes
|--------------------------------------------------------------------------
|
| Routes within this group require user authentication. This is where you
| define routes that are only accessible to logged-in users.
|
*/

Route::middleware(['auth', 'verified'])->group(function () {
    // Dashboard
    Route::get('/dashboard', function () {
        return Inertia::render('Dashboard');
    })->name('dashboard');

    // Application-specific routes
    Route::get('/phonebook', fn () => Inertia::render('LoggedinPages/Phonebook/Index'))->name('phonebook');
    Route::get('/tatmaps', fn () => Inertia::render('LoggedinPages/TATmaps/Index'))->name('tatmaps');
    Route::get('/servicedesk', fn () => Inertia::render('LoggedinPages/ServiceDesk/Index'))->name('servicedesk');
    Route::get('/trainingrequest', fn () => Inertia::render('LoggedinPages/TrainingRequest/Index'))->name('trainingrequest');
    Route::get('/homeofficerequest', [HomeOfficeRequestController::class, 'createForm'])
        ->name('homeofficerequest');
    Route::get('/myapplications', fn () => Inertia::render('LoggedinPages/MyApplications/Index'))->name('myapplications');

    // Home Office Request submission route
    Route::post('/home-office-requests', [HomeOfficeRequestController::class, 'store'])->middleware('auth')->name('home-office-requests.store');
});

/*
|--------------------------------------------------------------------------
| Profile Routes
|--------------------------------------------------------------------------
|
| Routes for user profile management. These include viewing and editing profile
| information, as well as deleting the user account.
|
*/

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});
